name: Execute checks & tests
on:
  push:
    branches-ignore:
      - main
jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install spaces-cli
        run: bun install -g spaces-cli
      - name: Download .env file
        run: |
          spaces-cli down /api/development.env -o ".env" \
            -r ${{ secrets.SPACE_REGION }} -s ${{ secrets.SPACE_NAME }} \
            -k ${{ secrets.SPACE_SECRET }} -i ${{ secrets.SPACE_KEY }}
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Run Biome Checks
        run: bun run check
      - name: Run unit tests
        run: bun run test